### ISSUE TITLE
question:  if (!getCurrentPackageInfo) in loop, meant to do this ?

### ISSUE THREAD

**Issue by bung87** [jchv/OpenWebView2Loader#4]
https://github.com/jchv/OpenWebView2Loader/blob/f3f908f90613c01e31bcadba6ecabbba45830902/Source/WebView2Loader.cpp#L719

```
    if (!getCurrentPackageInfo) {
      continue;
    }
```

**Comment by jchv** [comment]
It is meant to skip the calls to GetCurrentPackageInfo if it is not available. (GetCurrentPackageInfo is only available in Windows 8 and later.)

I believe this is how original WebView2Loader works.

**Comment by bung87** [comment]
but question is why it inside loop, why not outside loop

**Comment by jchv** [comment]
It still checks for `FindInstalledClientDllForChannel` for each channel, it only skips the `GetCurrentPackageInfo` part of the loop. The logic follows the official WebView2Loader. For each channel, the `FindInstalledClientDllForChannel` check occurs, then the `GetCurrentPackageInfo` check occurs in sequence, in the same loop.

```cpp
  for (int i = 0; i < kNumChannels; i++) {
    channel =
        preference == WebView2ReleaseChannelPreference::kCanary ? 4 - i : i;

    ...

    for (UINT32 j = 0; j < cPackages; j++) {
      if (_wcsicmp(packages[j].packageFamilyName,
                   kChannelPackageFamilyName[channel]) == 0) { // <-- channel variable
        package = &packages[j];
        break;
      }
    }
```

I don't think it is necessary to call `GetCurrentPackageInfo` more than once, but OpenWebView2Loader does exactly what WebView2Loader does, unless I made a mistake.

**Comment by bung87** [comment]
Thanks for reply,  does microsoft open source the webview2loader ? since you know the details.

**Comment by jchv** [comment]
Unfortunately I don't think so, although as far as I know, the binary itself is permissively licensed. That's why I created this project.
