### ISSUE TITLE
question: why call getCurrentPackageInfoProc for geting version since FindInstalledClientDllForChannel already get version

### ISSUE THREAD

**Issue by bung87** [jchv/OpenWebView2Loader#5]
https://github.com/jchv/OpenWebView2Loader/blob/f3f908f90613c01e31bcadba6ecabbba45830902/Source/WebView2Loader.cpp#L719-L753

I've ported part of this project into nim language,  without part above , I think it works fine

btw calling `getCurrentPackageInfoProc` will results `APPMODEL_ERROR_NO_PACKAGE` on my win11, I just compile and run without installation steps.

**Comment by jchv** [comment]
Unfortunately, I am not sure.

The goal of OpenWebView2Loader is to mimic the exact behavior of the original WebView2Loader. If my code does not match WebView2Loader's behavior, I would like to fix it to match the identical behavior of WebView2Loader. But, I don't really understand the motivation behind all of the behaviors. I do not know if the "package info" calls are currently used at all, or if they will be used in the future.

**Comment by bung87** [comment]
Thanks for explanations, if the goal is that then the code is fine.
