### ISSUE TITLE
do you might I post this project link to WebView2Feedback repo for reference ?

### ISSUE THREAD

**Issue by bung87** [jchv/OpenWebView2Loader#6]
found the webview2 need en variables and modify registry to work, but I dont clear the details , on my win11 registry even dont have `kRedistOverrideKey` and `kEmbeddedOverrideKey`, so I want to ask there.
https://github.com/MicrosoftEdge/WebView2Feedback

**Comment by jchv** [comment]
I don't have anything against it. However, I suspect that it is likely Microsoft engineers would not be willing to refer to OpenWebView2Loader since it is unofficial.

**Comment by bung87** [comment]
![屏幕截图 2022-08-25 225214](https://user-images.githubusercontent.com/2238294/186967762-831f401c-e0de-4f20-955c-c52cd5c4c15f.png)

maybe I should ask here, if you have used x64dbg or similar tool, I've asked in a discord channel , and get confirmed " the variable store "C:\Users\crc32\AppData\Roaming\webview" size too small" , use `newString(MAX_PATH)` in nim , it still existed, do you have any idea, am stucked 3 days now, any help would be appreciate.
